DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS team;
DROP TABLE IF EXISTS workout;
DROP TABLE IF EXISTS exercise;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
  bootcamp_id INTEGER
  team_id INTEGER
);

CREATE TABLE workout (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  exercise_id INTEGER NOT NULL,
);

CREATE TABLE team (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
);

CREATE TABLE exercise(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL,
    length NUMBER UNIQUE NOT NULL,
    caloriesBurned NUMBER,
    video
)